### ISSUE TITLE
Typst 0.12 generates a few warnings

### ISSUE THREAD

**Issue by ondohotola** [Sematre/typst-letter-pro#13]
I am getting these warnings when using the new typst (on the Mac)

```
warning: `locate` with callback function is deprecated
    ┌─ @preview/letter-pro:2.1.0/src/lib.typ:164:12
    │  
164 │       footer: locate(loc => {
    │ ╭─────────────^
165 │ │       show: pad.with(top: 12pt, bottom: 12pt)
166 │ │       
167 │ │       let current-page = loc.page()
    · │
188 │ │       )
189 │ │     }),
    │ ╰──────^
    │  
    = hint: use a `context` expression instead

warning: calling `counter.final` with a location is deprecated
    ┌─ @preview/letter-pro:2.1.0/src/lib.typ:168:23
    │
168 │       let page-count = counter(page).final(loc).at(0)
    │                        ^^^^^^^^^^^^^^^^^^^^^^^^
    │
    = hint: try removing the location argument
```

I have no clue how to fix these nor would I know what a Pull Request would be/look like :-)-O

**Comment by Sematre** [comment]
This deprecation warning has been fixed yesterday in #12, but I haven't made a new release yet. The new release will be published soon. I'll let you know here when it's published.

**Comment by ondohotola** [comment]
Thanks

**Comment by Sematre** [comment]
A new version has been released. Until typst/packages#1189 has been merged, you can follow the [alternative installation instructions](https://github.com/Sematre/typst-letter-pro?tab=readme-ov-file#usage) in the README.
