### ISSUE TITLE
Can I turn off the page number on the first page?

### ISSUE THREAD

**Issue by ondohotola** [Sematre/typst-letter-pro#15]
How would I turn off he page numbering for the first page only?

If it is documented somewhere feel free to point me there, I am not averse to RTFM

**Comment by Sematre** [comment]
With the `page-numbering` parameter, you can define, how the page numbers are formatted throughout the document. By using an `if` case, you can make the output conditional.

```typst
#show: letter-simple.with(
  // [...]
  page-numbering: (current-page, page-count) => if(current-page > 1) {[
    Page #current-page of #page-count
  ]},
)
```

**Comment by ondohotola** [comment]
Thank you so much

**Comment by ondohotola** [comment]
Thank you so much.

If I recall correctly (am on my iPad now) the page number does not appear on a one page letter, so I wonder it, eventually, this could be tied to a switch.

**Comment by Sematre** [comment]
Although it would be possible to implement this functionality directly into this template, I would like the API to be not overblown with features. Especially like in this case, where the user can implement this behavior easily themselves.

**Comment by ondohotola** [comment]
works, thanks.
