### ISSUE TITLE
Deprecation warnings

### ISSUE THREAD

**Issue by Stern1710** [Sematre/typst-letter-pro#16]
When using this template with Typst 0.12, Typst gives me 2 deprecation warnings from for the template. These are:

> locate with callback function is deprecated 
> Calling counter.final with a location is deprecated 

The project works perfectly fine, without any troubles, but this should probably be replaced at some point. Typst recommends using `context` or removing the location argument.
I would fix this myself, however, I have no knowledge on how to work with the template source.

**Comment by Sematre** [comment]
This deprecation warning has been fixed in #12, but I haven't made a new release yet. I will make a new release tomorrow. I'll let you know here when it's published.

**Comment by Sematre** [comment]
A new version has been released. Until typst/packages#1189 has been merged, you can follow the [alternative installation instructions](https://github.com/Sematre/typst-letter-pro?tab=readme-ov-file#usage) in the README.
