### ISSUE TITLE
Add optional argument for font

### ISSUE THREAD

**Issue by jnsdrtlf** [Sematre/typst-letter-pro#2]
I like your choice of Source Sans Pro as a neutral, sans serif font. However, sometimes it's nice to have some choice. Simply putting `#set text(font: "Some other font")` at the beginning of the document does not work as it will be overwritten in the template. Setting it in the body also does not work as it will only apply to the body.

I propose adding an optional option `font` to the template, with its default set to the current font – or alternatively drop the `#set text(font: ...)` entirely from the template. I personally prefer the first option.

If you'd like I'd be happy to provide a pull request later.

**Comment by Sematre** [comment]
Making is configurable is fine with me. But I would like to keep a default font that is compatible with automated letter processing software. 

Deutsche Post for example does **not** recommend the following font styles:
![Screenshot from 2024-02-24 20-00-14](https://github.com/Sematre/typst-letter-pro/assets/7118368/dee2980a-e47a-412b-a326-1dbdab94fa09)
(from [Deutsche Post / Automationsfähige Briefsendungen / Page 12](https://www.deutschepost.de/dam/dpag/images/P_p/printmailing/downloads/dp-automationsfaehige-briefsendungen-2024.pdf))

They recommend the following fonts:

> Standard fonts such as Arial, Frutiger,
> Helvetica, Times and Univers are easily
> machine-readable.

(from [Deutsche Post / Automationsfähige Briefsendungen / Page 12](https://www.deutschepost.de/dam/dpag/images/P_p/printmailing/downloads/dp-automationsfaehige-briefsendungen-2024.pdf))

**Comment by jnsdrtlf** [comment]
Oh, thanks for these resources! Thats super interesting!

I'll make the changes and create a pull request. Though not today, I'll probably do it by tomorrow.
