### ISSUE TITLE
Sender name is mandatory in `letter-simple`

### ISSUE THREAD

**Issue by Morwdan** [Sematre/typst-letter-pro#21]
Creating a letter without a sender name via `letter-simple` results in the following error…:

```
error: expected string or array, found none
    ┌─ @preview/letter-pro:3.0.0/src/lib.typ:539:12
    │
539 │     author: sender.name,
    │             ^^^^^^^^^^^
```

…as the sender name is also used to specify the document author (which [doesn’t seem to accept](https://typst.app/docs/reference/model/document/#parameters-author) `none`):

https://github.com/Sematre/typst-letter-pro/blob/0bc8f4cb5fdb2b35701dacb2a800082712a088a9/src/lib.typ#L536-L540

According to the documentation of `letter-simple`, the sender name can be none, so I assume this behavior is not intended. I worked around the issue with this change, but being new to Typst, there is probably a cleaner fix:

```typ
  // Configure page and text properties.
  if sender.name != none {
    set document(
      title: subject,
      author: sender.name
    )
  }
  else {
    set document(
      title: subject,
    )
  }
```

And thanks for this project!

**Comment by Sematre** [comment]
Thanks for reaching out. This is indeed a bug. I'll open a pull request.
