### ISSUE TITLE
Some links to Deutsche Post broken

### ISSUE THREAD

**Issue by Mastermindaxe** [Sematre/typst-letter-pro#9]
Hi there, amazing library! <3

Some links in the documentation to Deutsche Post are broken. Eg: https://www.deutschepost.de/de/b/briefvorlagen/beschwerden.html#Einspruch does not work anymore

**Comment by Mastermindaxe** [comment]
I'll try and update these myself and provide a PR if I have some time next week. This is just to let you know and track the issue

**Comment by Sematre** [comment]
Thanks for letting me know. After looking around a bit, I was unable to find the templates anymore. This leads me to believe that they removed this content entirely. Luckily, I archived these links last year.

As a workaround, I will change these links to the archived ones. If you manage to find the new location, feel free to open a pull request.
